'use client';
import { useEffect,useMemo,useState } from 'react';

type Decision={strategy_id:string;index:string;utility:number;expected_value:number;cvar95:number;stress_loss:number;transaction_cost:number;decision:string;reasons?:string[]};
type Position={strategyPositionId:string;strategyId:string;index?:string;status:string;unrealizedPnl?:number;realizedPnl?:number;maxLoss?:number;maxProfit?:number;markStatus?:string;updatedAt?:string;netGreeks?:Record<string,number>;legs?:Array<{side?:string;symbol?:string;strike?:number;optionType?:string;entryFill?:number;currentPrice?:number}>};
type Radar={success:boolean;updatedAt?:string;sessionStatus?:string;huntActive?:boolean;selectionAuthority?:string;streamStatus?:{connected?:boolean;subscribed?:number;lastTickAt?:string};quantDecision?:{engine?:string;model?:string;decision?:string;noTradeUtility?:number;selected?:Decision[];ranked?:Decision[];rejected?:Decision[];portfolioRisk?:{pass?:boolean;stressLoss?:number;greeks?:Record<string,number>;limits?:Record<string,number>}};strategyBook?:{open?:Position[];closed?:Position[]};error?:string};
const n=(v?:number,d=2)=>v==null?'—':v.toLocaleString('en-IN',{maximumFractionDigits:d});
const money=(v?:number)=>v==null?'—':`₹${n(v,0)}`;
const label=(s?:string)=>s?.replaceAll('_',' ')??'—';
export default function QuantIndexOptionsPanel({refreshToken=0}:{refreshToken?:number}){
 const [radar,setRadar]=useState<Radar|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();let timer:number|undefined;let busy=false;const run=async()=>{if(busy||c.signal.aborted)return;busy=true;try{const r=await fetch('/api/index-options',{cache:'no-store',signal:c.signal});const d=await r.json() as Radar;if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);setRadar(d)}catch(e){if(!c.signal.aborted)setRadar({success:false,error:e instanceof Error?e.message:'Quant desk unavailable'})}finally{busy=false;setLoading(false);if(!c.signal.aborted&&radar?.huntActive!==false)timer=window.setTimeout(run,5000)}};run();return()=>{c.abort();if(timer)window.clearTimeout(timer)}},[refreshToken]);
 const q=radar?.quantDecision;const ranked=q?.ranked??[];const open=radar?.strategyBook?.open??[];const greek=q?.portfolioRisk?.greeks??{};
 const top=useMemo(()=>ranked.slice(0,12),[ranked]);
 return <section className="ix-radar space-y-3" aria-label="Quant V2 index options desk">
  <div className="desk-card signal-widget signal-widget--radar p-3 sm:p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="signal-live-orb"/><h2 className="desk-panel-title">INDEX OPTIONS · QUANT V2</h2></div><p className="mt-1 text-[11px] text-[var(--fg-muted)]">Common-distribution repricing · EV/CVaR · portfolio Greeks · stress-governed durable execution</p></div><div className="flex flex-wrap gap-1.5"><span className="desk-pill desk-pill--ok">SOLE SELECTION AUTHORITY</span><span className="desk-pill desk-pill--muted">{q?.model?label(q.model):'Loading model'}</span><span className={radar?.streamStatus?.connected?'desk-pill desk-pill--ok':'desk-pill desk-pill--warn'}>{radar?.streamStatus?.connected?'Stream live':'REST fallback'}</span><span className="desk-pill desk-pill--muted">{radar?.sessionStatus??'—'}</span></div></div></div>
  {radar?.error&&<div className="desk-card p-3 text-red-500">{radar.error}</div>}
  <div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{[['Decision',q?.decision],['Candidates',ranked.length],['Selected',q?.selected?.length??0],['Open',open.length],['Δ',n(greek.delta,3)],['Γ',n(greek.gamma,5)],['Θ',n(greek.theta,2)],['Vega',n(greek.vega,2)]].map(([k,v])=><div key={String(k)} className="desk-card p-3"><div className="text-[9px] uppercase tracking-wider text-[var(--fg-subtle)]">{k}</div><div className="mt-1 font-bold tabular-nums">{String(v??'—')}</div></div>)}</div>
  <div className="grid gap-2 md:grid-cols-3"><div className="desk-card p-3"><div className="desk-panel-title">PORTFOLIO RISK GOVERNOR</div><div className="mt-2 text-xl font-bold">{q?.portfolioRisk?.pass===false?'BLOCKED':'WITHIN LIMITS'}</div><div className="mt-2 text-[10px] text-[var(--fg-muted)]">Stress loss {money(q?.portfolioRisk?.stressLoss)} · hard portfolio admission before durable lock</div></div><div className="desk-card p-3"><div className="desk-panel-title">NO-TRADE BENCHMARK</div><div className="mt-2 text-xl font-bold tabular-nums">Utility {n(q?.noTradeUtility,2)}</div><div className="mt-2 text-[10px] text-[var(--fg-muted)]">A structure must produce positive utility after costs, tail, Greek and concentration penalties.</div></div><div className="desk-card p-3"><div className="desk-panel-title">MARKET DECISION</div><div className="mt-2 text-xl font-bold">{q?.decision??(loading?'CALCULATING':'NO TRADE')}</div><div className="mt-2 text-[10px] text-[var(--fg-muted)]">{q?.engine??radar?.selectionAuthority??'INDEX_OPTIONS_QUANT_V2'}</div></div></div>
  <div className="desk-card overflow-x-auto p-3"><div className="desk-panel-title">STRUCTURE OPTIMIZER · COMMON DISTRIBUTION</div><table className="mt-3 w-full min-w-[850px] text-left text-[10px]"><thead className="text-[var(--fg-subtle)]"><tr><th className="py-2">Rank</th><th>Index</th><th>Structure</th><th>Utility</th><th>EV</th><th>CVaR95</th><th>Stress</th><th>Cost</th><th>Decision</th><th>Reason</th></tr></thead><tbody>{top.map((d,i)=><tr key={`${d.strategy_id}-${d.index}-${i}`} className="border-t border-[var(--terminal-line)]"><td className="py-2">{i+1}</td><td>{d.index}</td><td className="font-bold">{label(d.strategy_id)}</td><td className={d.utility>0?'text-emerald-600':'text-red-500'}>{n(d.utility)}</td><td>{money(d.expected_value)}</td><td>{money(d.cvar95)}</td><td>{money(d.stress_loss)}</td><td>{money(d.transaction_cost)}</td><td><span className={d.decision==='ADMIT'?'desk-pill desk-pill--ok':'desk-pill desk-pill--muted'}>{d.decision}</span></td><td>{label(d.reasons?.join(' · '))}</td></tr>)}</tbody></table>{!top.length&&!loading&&<div className="py-5 text-center text-[var(--fg-muted)]">No repriced structures available.</div>}</div>
  <div className="desk-card overflow-x-auto p-3"><div className="flex items-center justify-between"><div><div className="desk-panel-title">DURABLE QUANT STRATEGY BOOK</div><div className="mt-1 text-[10px] text-[var(--fg-muted)]">Canonical positions · no duplicate legacy seller authority</div></div><span className="desk-pill desk-pill--ok">{open.length} open</span></div><table className="mt-3 w-full min-w-[850px] text-left text-[10px]"><thead className="text-[var(--fg-subtle)]"><tr><th className="py-2">Index</th><th>Strategy</th><th>P&L</th><th>Max loss</th><th>Δ</th><th>Γ</th><th>Θ</th><th>Vega</th><th>Mark</th><th>Legs</th></tr></thead><tbody>{open.map(p=><tr key={p.strategyPositionId} className="border-t border-[var(--terminal-line)]"><td className="py-2">{p.index}</td><td className="font-bold">{label(p.strategyId)}</td><td className={(p.unrealizedPnl??0)>=0?'text-emerald-600':'text-red-500'}>{money(p.unrealizedPnl)}</td><td>{money(p.maxLoss)}</td><td>{n(p.netGreeks?.delta,3)}</td><td>{n(p.netGreeks?.gamma,5)}</td><td>{n(p.netGreeks?.theta,2)}</td><td>{n(p.netGreeks?.vega,2)}</td><td>{p.markStatus??'—'}</td><td>{p.legs?.length??0}</td></tr>)}</tbody></table>{!open.length&&<div className="py-5 text-center text-[var(--fg-muted)]">No open Quant V2 position · NO TRADE is valid.</div>}</div>
 </section>
}