#Requires -Version 5.1
# Prepare Cloudflare Tunnel for Docker Compose:
#  - Copy host credentials into config/cloudflare/credentials.json
#  - Write config/cloudflare/config.docker.yml (frontend service, not localhost)
# Exit 0 = ready, 2 = missing setup (caller may skip tunnel)

$ErrorActionPreference = "Stop"

$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$HostCfDir = Join-Path $env:USERPROFILE ".cloudflared"
$HostConfig = Join-Path $HostCfDir "config.yml"
$OutDir = Join-Path $ProjectRoot "config\cloudflare"
$OutConfig = Join-Path $OutDir "config.docker.yml"
$CredDest = Join-Path $OutDir "credentials.json"

if (-not (Test-Path $HostConfig)) {
  Write-Host "[WARN] Missing $HostConfig - run config\startup\setup-cloudflare-tunnel.bat once" -ForegroundColor Yellow
  exit 2
}

$hostYaml = Get-Content -Path $HostConfig -Raw -ErrorAction Stop
$tunnelName = "iros-desk"
if ($hostYaml -match '(?m)^\s*tunnel:\s*(.+)\s*$') {
  $tunnelName = $Matches[1].Trim().Trim('"').Trim("'")
}

$credSrc = $null
if ($hostYaml -match '(?m)^\s*credentials-file:\s*(.+)\s*$') {
  $credSrc = $Matches[1].Trim().Trim('"').Trim("'") -replace '/', '\'
}
if (-not $credSrc -or -not (Test-Path $credSrc)) {
  $jsons = Get-ChildItem -Path $HostCfDir -Filter "*.json" -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -like "*-*-*-*-*.json" }
  if ($jsons) { $credSrc = $jsons[0].FullName }
}
if (-not $credSrc -or -not (Test-Path $credSrc)) {
  Write-Host "[WARN] No tunnel credentials JSON in $HostCfDir" -ForegroundColor Yellow
  exit 2
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
Copy-Item -Path $credSrc -Destination $CredDest -Force

$hostnames = New-Object System.Collections.Generic.List[string]
foreach ($m in [regex]::Matches($hostYaml, '(?m)^\s*-\s*hostname:\s*(\S+)\s*$')) {
  $h = $m.Groups[1].Value.Trim()
  if ($h -and -not $hostnames.Contains($h)) { [void]$hostnames.Add($h) }
}
if ($hostnames.Count -eq 0) {
  foreach ($h in @("sigq.in", "www.sigq.in", "iros.sigq.in")) { [void]$hostnames.Add($h) }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Auto-generated by prepare-docker-tunnel.ps1 - do not edit by hand")
[void]$sb.AppendLine("tunnel: $tunnelName")
[void]$sb.AppendLine("credentials-file: /etc/cloudflared/credentials.json")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("ingress:")
foreach ($h in $hostnames) {
  [void]$sb.AppendLine("  - hostname: $h")
  [void]$sb.AppendLine("    service: http://frontend:3000")
}
[void]$sb.AppendLine("  - service: http_status:404")

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutConfig, $sb.ToString(), $utf8)

Write-Host "[OK] Docker tunnel config ready ($tunnelName -> frontend:3000)" -ForegroundColor Green
Write-Host "     $OutConfig"
Write-Host "     credentials: $CredDest"
exit 0
