#Requires -Version 5.1
# Prepare Cloudflare Tunnel for Docker Compose:
#  - Copy host credentials into config/cloudflare/credentials.json
#  - Write config/cloudflare/config.docker.yml (frontend service, not localhost)
# Exit 0 = ready, 2 = missing setup (caller may skip tunnel)

$ErrorActionPreference = "Stop"

$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$HostCfDir = Join-Path $env:USERPROFILE ".cloudflared"
$HostConfig = Join-Path $HostCfDir "config.yml"
$OutDir = Join-Path $ProjectRoot "config\cloudflare"
$OutConfig = Join-Path $OutDir "config.docker.yml"
$CredDest = Join-Path $OutDir "credentials.json"

if (-not (Test-Path $HostConfig)) {
  Write-Host "[WARN] Missing $HostConfig - run config\startup\setup-cloudflare-tunnel.bat once" -ForegroundColor Yellow
  exit 2
}

$hostYaml = Get-Content -Path $HostConfig -Raw -ErrorAction Stop
$tunnelName = "iros-desk"
if ($hostYaml -match '(?m)^\s*tunnel:\s*(.+)\s*$') {
  $tunnelName = $Matches[1].Trim().Trim('"').Trim("'")
}

$credSrc = $null
if ($hostYaml -match '(?m)^\s*credentials-file:\s*(.+)\s*$') {
  $credSrc = $Matches[1].Trim().Trim('"').Trim("'") -replace '/', '\'
}
if (-not $credSrc -or -not (Test-Path $credSrc)) {
  $jsons = Get-ChildItem -Path $HostCfDir -Filter "*.json" -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -like "*-*-*-*-*.json" }
  if ($jsons) { $credSrc = $jsons[0].FullName }
}
if (-not $credSrc -or -not (Test-Path $credSrc)) {
  Write-Host "[WARN] No tunnel credentials JSON in $HostCfDir" -ForegroundColor Yellow
  exit 2
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
Copy-Item -Path $credSrc -Destination $CredDest -Force

# Prefer host config hostnames/services. Map localhost → Docker services.
# calendar.sigq.in → panchang-api:8088; other hostnames → frontend:3000 by default.
$ingressPairs = New-Object System.Collections.Generic.List[object]
foreach ($m in [regex]::Matches($hostYaml, '(?ms)^\s*-\s*hostname:\s*(\S+)\s*\r?\n\s*service:\s*(\S+)\s*$')) {
  $h = $m.Groups[1].Value.Trim()
  $svc = $m.Groups[2].Value.Trim()
  if (-not $h) { continue }
  if ($svc -match '127\.0\.0\.1:8088' -or $svc -match 'localhost:8088') {
    $svc = "http://panchang-api:8088"
  } elseif ($svc -match '127\.0\.0\.1:3000' -or $svc -match 'localhost:3000') {
    $svc = "http://frontend:3000"
  }
  [void]$ingressPairs.Add([pscustomobject]@{ Hostname = $h; Service = $svc })
}
if ($ingressPairs.Count -eq 0) {
  [void]$ingressPairs.Add([pscustomobject]@{ Hostname = "calendar.sigq.in"; Service = "http://panchang-api:8088" })
  [void]$ingressPairs.Add([pscustomobject]@{ Hostname = "sigq.in"; Service = "http://frontend:3000" })
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Auto-generated by prepare-docker-tunnel.ps1 - do not edit by hand")
[void]$sb.AppendLine("tunnel: $tunnelName")
[void]$sb.AppendLine("credentials-file: /etc/cloudflared/credentials.json")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("ingress:")
foreach ($pair in $ingressPairs) {
  [void]$sb.AppendLine("  - hostname: $($pair.Hostname)")
  [void]$sb.AppendLine("    service: $($pair.Service)")
}
[void]$sb.AppendLine("  - service: http_status:404")

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutConfig, $sb.ToString(), $utf8)

$summary = ($ingressPairs | ForEach-Object { "$($_.Hostname)->$($_.Service)" }) -join ", "
Write-Host "[OK] Docker tunnel config ready ($tunnelName: $summary)" -ForegroundColor Green
Write-Host "     $OutConfig"
Write-Host "     credentials: $CredDest"
exit 0
