from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANGEL = ROOT / "backend/app/services/angel_one_feed.py"
ROUTE = ROOT / "iros-terminal/app/api/market-data/route.ts"
COMPOSE = ROOT / "docker-compose.yml"
TEST = ROOT / "backend/tests/test_market_data_read_scaling.py"

angel = ANGEL.read_text(encoding="utf-8")
old_loader = '''def _load_last_snapshot() -> dict[str, Any] | None:\n    from .market_snapshot_store import readable_market_snapshot_path\n\n    for path in (_snapshot_path(), readable_market_snapshot_path()):\n        try:\n            payload = json.loads(path.read_text(encoding="utf-8"))\n            if isinstance(payload, dict):\n                return _normalize_snapshot(payload)\n        except Exception:\n            continue\n    return None\n'''
new_loader = '''_MARKET_SNAPSHOT_MEMORY_LOCK = threading.Lock()\n_MARKET_SNAPSHOT_MEMORY: dict[str, Any] | None = None\n_MARKET_SNAPSHOT_MEMORY_PATH: str | None = None\n_MARKET_SNAPSHOT_MEMORY_MTIME_NS: int | None = None\n\n\ndef _load_last_snapshot() -> dict[str, Any] | None:\n    \"\"\"Return the persisted snapshot without reparsing the same JSON per viewer.\n\n    The market collector writes snapshots independently.  The read path keys the\n    in-process cache by file path + nanosecond mtime, so a new deterministic\n    snapshot is observed immediately while thousands of readers share one parse.\n    \"\"\"\n    from .market_snapshot_store import readable_market_snapshot_path\n\n    global _MARKET_SNAPSHOT_MEMORY\n    global _MARKET_SNAPSHOT_MEMORY_PATH\n    global _MARKET_SNAPSHOT_MEMORY_MTIME_NS\n\n    for path in (_snapshot_path(), readable_market_snapshot_path()):\n        try:\n            stat = path.stat()\n        except Exception:\n            continue\n        path_key = str(path.resolve())\n        mtime_ns = int(stat.st_mtime_ns)\n        with _MARKET_SNAPSHOT_MEMORY_LOCK:\n            if (\n                _MARKET_SNAPSHOT_MEMORY is not None\n                and _MARKET_SNAPSHOT_MEMORY_PATH == path_key\n                and _MARKET_SNAPSHOT_MEMORY_MTIME_NS == mtime_ns\n            ):\n                return dict(_MARKET_SNAPSHOT_MEMORY)\n            try:\n                payload = json.loads(path.read_text(encoding="utf-8"))\n                if not isinstance(payload, dict):\n                    continue\n                normalized = _normalize_snapshot(payload)\n                _MARKET_SNAPSHOT_MEMORY = normalized\n                _MARKET_SNAPSHOT_MEMORY_PATH = path_key\n                _MARKET_SNAPSHOT_MEMORY_MTIME_NS = mtime_ns\n                return dict(normalized)\n            except Exception:\n                continue\n    return None\n'''
if old_loader not in angel:
    raise SystemExit("snapshot loader pattern not found")
angel = angel.replace(old_loader, new_loader, 1)
ANGEL.write_text(angel, encoding="utf-8")

route = '''import { NextResponse } from "next/server";\n\nexport const runtime = "nodejs";\nconst BACKEND_URL = process.env.MARKET_API_URL ?? "http://127.0.0.1:8000";\nconst CACHE_TTL_MS = Math.max(250, Number(process.env.MARKET_READ_CACHE_MS ?? 2000));\nconst STALE_TTL_MS = Math.max(CACHE_TTL_MS, Number(process.env.MARKET_READ_STALE_MS ?? 30000));\nconst BACKEND_TIMEOUT_MS = Math.max(1000, Number(process.env.MARKET_READ_BACKEND_TIMEOUT_MS ?? 8000));\n\ntype CacheEntry = { data: unknown; expiresAt: number; staleUntil: number };\nconst cache = new Map<string, CacheEntry>();\nconst inFlight = new Map<string, Promise<unknown>>();\n\nfunction reply(data: unknown, state: string, status = 200) {\n  return NextResponse.json(data, {\n    status,\n    headers: {\n      "x-iros-market-cache": state,\n      "cache-control": "private, no-store, max-age=0",\n    },\n  });\n}\n\nasync function fetchBackend(url: URL): Promise<unknown> {\n  const res = await fetch(url.toString(), {\n    cache: "no-store",\n    signal: AbortSignal.timeout(BACKEND_TIMEOUT_MS),\n  });\n  if (!res.ok) {\n    const detail = await res.text();\n    throw new Error(detail || `Backend HTTP ${res.status}`);\n  }\n  return res.json();\n}\n\nexport async function GET(request: Request) {\n  const requestUrl = new URL(request.url);\n  const pool = requestUrl.searchParams.get("pool");\n  const prompt = requestUrl.searchParams.get("prompt");\n  const backendUrl = new URL(`${BACKEND_URL}/api/market-data`);\n  if (pool) backendUrl.searchParams.set("pool", pool);\n  if (prompt) backendUrl.searchParams.set("prompt", prompt);\n\n  // Custom prompts are not shared between users. Normal dashboard reads are.\n  const key = prompt ? `private:${crypto.randomUUID()}` : `pool:${pool ?? "default"}`;\n  const now = Date.now();\n  const cached = cache.get(key);\n  if (cached && now < cached.expiresAt) return reply(cached.data, "HIT");\n\n  try {\n    let pending = inFlight.get(key);\n    const coalesced = Boolean(pending);\n    if (!pending) {\n      pending = fetchBackend(backendUrl);\n      inFlight.set(key, pending);\n    }\n    const data = await pending;\n    cache.set(key, {\n      data,\n      expiresAt: Date.now() + CACHE_TTL_MS,\n      staleUntil: Date.now() + STALE_TTL_MS,\n    });\n    return reply(data, coalesced ? "COALESCED" : "MISS");\n  } catch (err) {\n    const stale = cache.get(key);\n    if (stale && Date.now() < stale.staleUntil) return reply(stale.data, "STALE");\n    const message = err instanceof Error ? err.message : "Backend unreachable";\n    return reply({ success: false, error: message }, "ERROR", 503);\n  } finally {\n    inFlight.delete(key);\n  }\n}\n'''
ROUTE.write_text(route, encoding="utf-8")

compose = COMPOSE.read_text(encoding="utf-8")
if 'FRONTEND_WORKERS: "6"' not in compose:
    raise SystemExit("frontend worker setting not found")
compose = compose.replace('FRONTEND_WORKERS: "6"', 'FRONTEND_WORKERS: "1"', 1)
if 'MARKET_READ_CACHE_MS:' not in compose:
    compose = compose.replace(
        '      FRONTEND_WORKERS: "1"\n',
        '      FRONTEND_WORKERS: "1"\n      MARKET_READ_CACHE_MS: "2000"\n      MARKET_READ_STALE_MS: "30000"\n      MARKET_READ_BACKEND_TIMEOUT_MS: "8000"\n',
        1,
    )
COMPOSE.write_text(compose, encoding="utf-8")

TEST.write_text('''import json\nfrom concurrent.futures import ThreadPoolExecutor\nfrom pathlib import Path\n\nfrom app.services import angel_one_feed as feed\n\n\ndef test_market_snapshot_loader_parses_once_for_same_mtime(tmp_path, monkeypatch):\n    snap = tmp_path / "snapshot.json"\n    snap.write_text(json.dumps({"success": True, "stocks": [], "updatedAt": "2026-08-28T09:00:00+00:00"}), encoding="utf-8")\n    monkeypatch.setattr(feed, "_snapshot_path", lambda: snap)\n    monkeypatch.setattr(feed, "_normalize_snapshot", lambda payload: payload)\n    feed._MARKET_SNAPSHOT_MEMORY = None\n    feed._MARKET_SNAPSHOT_MEMORY_PATH = None\n    feed._MARKET_SNAPSHOT_MEMORY_MTIME_NS = None\n\n    original = Path.read_text\n    calls = {"n": 0}\n\n    def counted(self, *args, **kwargs):\n        if self == snap:\n            calls["n"] += 1\n        return original(self, *args, **kwargs)\n\n    monkeypatch.setattr(Path, "read_text", counted)\n    with ThreadPoolExecutor(max_workers=32) as executor:\n        rows = list(executor.map(lambda _: feed._load_last_snapshot(), range(200)))\n    assert all(row and row["success"] for row in rows)\n    assert calls["n"] == 1\n\n\ndef test_market_snapshot_loader_invalidates_on_file_change(tmp_path, monkeypatch):\n    snap = tmp_path / "snapshot.json"\n    snap.write_text(json.dumps({"success": True, "version": 1}), encoding="utf-8")\n    monkeypatch.setattr(feed, "_snapshot_path", lambda: snap)\n    monkeypatch.setattr(feed, "_normalize_snapshot", lambda payload: payload)\n    feed._MARKET_SNAPSHOT_MEMORY = None\n    feed._MARKET_SNAPSHOT_MEMORY_PATH = None\n    feed._MARKET_SNAPSHOT_MEMORY_MTIME_NS = None\n    assert feed._load_last_snapshot()["version"] == 1\n    snap.write_text(json.dumps({"success": True, "version": 2, "padding": "changed"}), encoding="utf-8")\n    assert feed._load_last_snapshot()["version"] == 2\n''', encoding="utf-8")

print("market read scaling patch applied")
